### ISSUE TITLE
Unhandled Exception: System.NotSupportedException: No imaging component suitable to complete this operation was found. 

### ISSUE THREAD

**Issue by twobob** [mckamey/exif-utils#1]
D:\REPOS\exif-utils.net-master\XmpUtils\XmpDemo\bin\Debug\XmpDemo.exe
Processing .\636307583846301509.jpg

`Unhandled Exception: System.NotSupportedException: No imaging component suitable to complete this operation was found. ---> System.Runtime.InteropServices.COMException (0x88982F50): The component cannot be found. (Exception from HRESULT: 0x88982F50)
   --- End of inner exception stack trace ---
   at MS.Internal.HRESULT.Check(Int32 hr)
   at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
   at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   at System.Windows.Media.Imaging.BitmapDecoder.Create(Stream bitmapStream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption)
   at XmpUtils.Xmp.XmpExtractor.LoadMetadata(Stream stream) in d:\REPOS\exif-utils.net-master\XmpUtils\XmpUtils\Xmp\XmpExtractor.cs:line 986
   at XmpUtils.Xmp.XmpExtractor.Extract(Stream stream, IEnumerable1 schemas) in d:\REPOS\exif-utils.net-master\XmpUtils\XmpUtils\Xmp\XmpExtractor.cs:line 77
   at XmpUtils.Xmp.XmpExtractor.Extract(String filename, IEnumerable1 schemas) in d:\REPOS\exif-utils.net-master\XmpUtils\XmpUtils\Xmp\XmpExtractor.cs:line 71
   at XmpUtils.Xmp.XmpPropertyCollection.LoadFromImage(String filename, IEnumerable1 schemas) in d:\REPOS\exif-utils.net-master\XmpUtils\XmpUtils\Xmp\XmpPropertyCollection.cs:line 761
   at XmpUtils.Xmp.XmpPropertyCollection.LoadFromImage(String filename, Enum[] schemas) in d:\REPOS\exif-utils.net-master\XmpUtils\XmpUtils\Xmp\XmpPropertyCollection.cs:line 756
   at XmpDemo.Program.Main() in d:\REPOS\exif-utils.net-master\XmpUtils\XmpDemo\Program.cs:line 62`

Did I miss including something?

**Comment by twobob** [comment]
windows 10 box, building on 2013

**Comment by twobob** [comment]
okay no I got it to run. must be an unhandled exception on getting passed a bad file or something.
Thanks
